database:
  # Note: This is only a local connection for development
  host: localhost
  port: 3306
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  dbName: InventoryController

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    #show-sql: true
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.dbName}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  region: us-east-1