

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:InventoryController;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        sql: info

encrypt:
  keyLength: 256
  iterationCount: 65536
  secretKeyFactory: PBKDF2WithHmacSHA256
  cipherInstance: AES/CBC/PKCS5Padding
  # secretKey:
  # salt:
  encryptionMethod: AES

server:
  port: 8081